# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tripless' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tripless

  target 'TriplessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TriplessUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
